"""Phase 9 dynamic extraction models

Revision ID: 461bc4adf94b
Revises: 7f5c6cf0bd4c
Create Date: 2026-08-07 10:57:40.371992+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic
revision: str = '461bc4adf94b'
down_revision: str | None = '7f5c6cf0bd4c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patent_extractions',
    sa.Column('research_run_id', sa.UUID(), nullable=False),
    sa.Column('patent_number', sa.String(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('assignee', sa.String(), nullable=True),
    sa.Column('publication_year', sa.String(), nullable=True),
    sa.Column('jurisdiction', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patent_extractions_id'), 'patent_extractions', ['id'], unique=False)
    op.create_index(op.f('ix_patent_extractions_patent_number'), 'patent_extractions', ['patent_number'], unique=False)
    op.create_index(op.f('ix_patent_extractions_research_run_id'), 'patent_extractions', ['research_run_id'], unique=False)
    op.create_table('extracted_parameters',
    sa.Column('patent_extraction_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('context', sa.Text(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('confidence', sa.String(), nullable=True),
    sa.Column('example_number', sa.String(), nullable=True),
    sa.Column('source_sentence', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['patent_extraction_id'], ['patent_extractions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_parameters_category'), 'extracted_parameters', ['category'], unique=False)
    op.create_index(op.f('ix_extracted_parameters_id'), 'extracted_parameters', ['id'], unique=False)
    op.create_index(op.f('ix_extracted_parameters_name'), 'extracted_parameters', ['name'], unique=False)
    op.create_index(op.f('ix_extracted_parameters_patent_extraction_id'), 'extracted_parameters', ['patent_extraction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_parameters_patent_extraction_id'), table_name='extracted_parameters')
    op.drop_index(op.f('ix_extracted_parameters_name'), table_name='extracted_parameters')
    op.drop_index(op.f('ix_extracted_parameters_id'), table_name='extracted_parameters')
    op.drop_index(op.f('ix_extracted_parameters_category'), table_name='extracted_parameters')
    op.drop_table('extracted_parameters')
    op.drop_index(op.f('ix_patent_extractions_research_run_id'), table_name='patent_extractions')
    op.drop_index(op.f('ix_patent_extractions_patent_number'), table_name='patent_extractions')
    op.drop_index(op.f('ix_patent_extractions_id'), table_name='patent_extractions')
    op.drop_table('patent_extractions')
    # ### end Alembic commands ###
