"""Add structured_data to ReportMetadata

Revision ID: 5bbebe1cf93c
Revises: 5741ae2ef6d9
Create Date: 2026-08-10 16:53:16.191115+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '5bbebe1cf93c'
down_revision: str | None = '5741ae2ef6d9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_metadata', sa.Column('structured_data', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_metadata', 'structured_data')
    # ### end Alembic commands ###
