"""Add title_signals and discovered_by_queries

Revision ID: 5741ae2ef6d9
Revises: 6706b38e3bb1
Create Date: 2026-08-10 13:31:15.165633+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '5741ae2ef6d9'
down_revision: str | None = '6706b38e3bb1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('search_results', sa.Column('title_signals', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('search_results', sa.Column('discovered_by_queries', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('search_results', 'discovered_by_queries')
    op.drop_column('search_results', 'title_signals')
    # ### end Alembic commands ###
