"""Add PAUSED status

Revision ID: cb96565b4162
Revises: 2e6b41158b18
Create Date: 2026-08-06 07:38:01.140493+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic
revision: str = 'cb96565b4162'
down_revision: str | None = '2e6b41158b18'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE runstatus ADD VALUE 'PAUSED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
