"""add_recipe_tables

Revision ID: 63a11035b031
Revises: 4cdfa17814ca
Create Date: 2026-08-17 12:50:27.948846+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '63a11035b031'
down_revision: str | None = '4cdfa17814ca'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_cycles',
    sa.Column('research_run_id', sa.UUID(), nullable=True),
    sa.Column('report_metadata_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('compound_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'STEP1', 'GENERATING', 'STEP2', 'STEP3', 'OPTIMIZING', 'STEP4', 'COMPLETED', 'FAILED', name='recipecyclestatus', create_constraint=True), server_default='PENDING', nullable=False),
    sa.Column('target_properties', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('competitor_data', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('patent_context_summary', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('selected_candidate_id', sa.UUID(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['report_metadata_id'], ['report_metadata.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_cycles_compound_name'), 'recipe_cycles', ['compound_name'], unique=False)
    op.create_index(op.f('ix_recipe_cycles_created_by'), 'recipe_cycles', ['created_by'], unique=False)
    op.create_index(op.f('ix_recipe_cycles_id'), 'recipe_cycles', ['id'], unique=False)
    op.create_index(op.f('ix_recipe_cycles_report_metadata_id'), 'recipe_cycles', ['report_metadata_id'], unique=False)
    op.create_index(op.f('ix_recipe_cycles_research_run_id'), 'recipe_cycles', ['research_run_id'], unique=False)
    op.create_index(op.f('ix_recipe_cycles_status'), 'recipe_cycles', ['status'], unique=False)
    op.create_table('recipe_candidates',
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('recipe_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('patent_references', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('evidence_coverage_score', sa.Integer(), nullable=False),
    sa.Column('is_selected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['recipe_cycles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_candidates_cycle_id'), 'recipe_candidates', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_recipe_candidates_id'), 'recipe_candidates', ['id'], unique=False)
    op.create_table('customer_trials',
    sa.Column('cycle_id', sa.UUID(), nullable=False),
    sa.Column('selected_candidate_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'OPTIMIZING', 'COMPLETED', 'FAILED', name='trialstatus', create_constraint=True), server_default='PENDING', nullable=False),
    sa.Column('feedback_text', sa.Text(), nullable=True),
    sa.Column('actual_values', postgresql.JSON(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('target_values', postgresql.JSON(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('selected_optimized_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['cycle_id'], ['recipe_cycles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['selected_candidate_id'], ['recipe_candidates.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_trials_created_by'), 'customer_trials', ['created_by'], unique=False)
    op.create_index(op.f('ix_customer_trials_cycle_id'), 'customer_trials', ['cycle_id'], unique=False)
    op.create_index(op.f('ix_customer_trials_id'), 'customer_trials', ['id'], unique=False)
    op.create_index(op.f('ix_customer_trials_selected_candidate_id'), 'customer_trials', ['selected_candidate_id'], unique=False)
    op.create_index(op.f('ix_customer_trials_status'), 'customer_trials', ['status'], unique=False)
    op.create_table('optimized_recipe_candidates',
    sa.Column('trial_id', sa.UUID(), nullable=False),
    sa.Column('revision_label', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('recipe_data', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('changed_parameters', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('predicted_impacts', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('is_selected', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trial_id'], ['customer_trials.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimized_recipe_candidates_id'), 'optimized_recipe_candidates', ['id'], unique=False)
    op.create_index(op.f('ix_optimized_recipe_candidates_trial_id'), 'optimized_recipe_candidates', ['trial_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_optimized_recipe_candidates_trial_id'), table_name='optimized_recipe_candidates')
    op.drop_index(op.f('ix_optimized_recipe_candidates_id'), table_name='optimized_recipe_candidates')
    op.drop_table('optimized_recipe_candidates')
    op.drop_index(op.f('ix_customer_trials_status'), table_name='customer_trials')
    op.drop_index(op.f('ix_customer_trials_selected_candidate_id'), table_name='customer_trials')
    op.drop_index(op.f('ix_customer_trials_id'), table_name='customer_trials')
    op.drop_index(op.f('ix_customer_trials_cycle_id'), table_name='customer_trials')
    op.drop_index(op.f('ix_customer_trials_created_by'), table_name='customer_trials')
    op.drop_table('customer_trials')
    op.drop_index(op.f('ix_recipe_candidates_id'), table_name='recipe_candidates')
    op.drop_index(op.f('ix_recipe_candidates_cycle_id'), table_name='recipe_candidates')
    op.drop_table('recipe_candidates')
    op.drop_index(op.f('ix_recipe_cycles_status'), table_name='recipe_cycles')
    op.drop_index(op.f('ix_recipe_cycles_research_run_id'), table_name='recipe_cycles')
    op.drop_index(op.f('ix_recipe_cycles_report_metadata_id'), table_name='recipe_cycles')
    op.drop_index(op.f('ix_recipe_cycles_id'), table_name='recipe_cycles')
    op.drop_index(op.f('ix_recipe_cycles_created_by'), table_name='recipe_cycles')
    op.drop_index(op.f('ix_recipe_cycles_compound_name'), table_name='recipe_cycles')
    op.drop_table('recipe_cycles')
    # ### end Alembic commands ###
