"""Add SearchQuery, SearchResult, ExtractionBatch models

Revision ID: 9c7e23e83fca
Revises: 461bc4adf94b
Create Date: 2026-08-10 12:10:14.693995+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '9c7e23e83fca'
down_revision: str | None = '461bc4adf94b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extraction_batches',
    sa.Column('research_run_id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.Integer(), nullable=False),
    sa.Column('patent_ids', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_input_tokens', sa.Integer(), nullable=False),
    sa.Column('actual_input_tokens', sa.Integer(), nullable=True),
    sa.Column('actual_output_tokens', sa.Integer(), nullable=True),
    sa.Column('total_tokens', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='batchstatus', create_constraint=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extraction_batches_id'), 'extraction_batches', ['id'], unique=False)
    op.create_index(op.f('ix_extraction_batches_research_run_id'), 'extraction_batches', ['research_run_id'], unique=False)
    op.create_table('search_queries',
    sa.Column('research_run_id', sa.UUID(), nullable=False),
    sa.Column('query_text', sa.String(length=500), nullable=False),
    sa.Column('field', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('jurisdiction', sa.String(length=10), nullable=True),
    sa.Column('date_start', sa.String(length=20), nullable=True),
    sa.Column('date_end', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SEARCHING', 'COMPLETED', 'FAILED', name='searchquerystatus', create_constraint=True), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_queries_id'), 'search_queries', ['id'], unique=False)
    op.create_index(op.f('ix_search_queries_research_run_id'), 'search_queries', ['research_run_id'], unique=False)
    op.create_table('search_results',
    sa.Column('research_run_id', sa.UUID(), nullable=False),
    sa.Column('search_query_id', sa.UUID(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('publication_number', sa.String(length=50), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('jurisdiction', sa.String(length=10), nullable=True),
    sa.Column('publication_date', sa.String(length=50), nullable=True),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('title_score', sa.Integer(), nullable=True),
    sa.Column('title_screening_status', sa.Enum('PENDING', 'STRONG', 'MEDIUM', 'WEAK', 'REJECT', name='titlescreeningstatus', create_constraint=True), nullable=False),
    sa.Column('gemini_score', sa.Integer(), nullable=True),
    sa.Column('gemini_decision', sa.String(length=20), nullable=True),
    sa.Column('gemini_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['research_run_id'], ['research_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_query_id'], ['search_queries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_results_id'), 'search_results', ['id'], unique=False)
    op.create_index(op.f('ix_search_results_publication_number'), 'search_results', ['publication_number'], unique=False)
    op.create_index(op.f('ix_search_results_research_run_id'), 'search_results', ['research_run_id'], unique=False)
    op.create_index(op.f('ix_search_results_search_query_id'), 'search_results', ['search_query_id'], unique=False)
    op.create_index(op.f('ix_search_results_title_screening_status'), 'search_results', ['title_screening_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_results_title_screening_status'), table_name='search_results')
    op.drop_index(op.f('ix_search_results_search_query_id'), table_name='search_results')
    op.drop_index(op.f('ix_search_results_research_run_id'), table_name='search_results')
    op.drop_index(op.f('ix_search_results_publication_number'), table_name='search_results')
    op.drop_index(op.f('ix_search_results_id'), table_name='search_results')
    op.drop_table('search_results')
    op.drop_index(op.f('ix_search_queries_research_run_id'), table_name='search_queries')
    op.drop_index(op.f('ix_search_queries_id'), table_name='search_queries')
    op.drop_table('search_queries')
    op.drop_index(op.f('ix_extraction_batches_research_run_id'), table_name='extraction_batches')
    op.drop_index(op.f('ix_extraction_batches_id'), table_name='extraction_batches')
    op.drop_table('extraction_batches')
    # ### end Alembic commands ###
