"""add discovery provenance fields to search_results and website_evidences to research_runs

Revision ID: 20260811_abc123def456
Revises: 20260811_add_selection_rank
Create Date: 2026-08-11

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20260811_abc123def456'
down_revision: Union[str, None] = '20260811_add_selection_rank'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add discovery provenance fields to search_results
    op.add_column('search_results', sa.Column('discovery_source', sa.String(length=20), nullable=True, server_default='NORMAL'))
    op.add_column('search_results', sa.Column('competitor_name', sa.String(length=255), nullable=True))
    op.add_column('search_results', sa.Column('website_domain', sa.String(length=255), nullable=True))
    op.add_column('search_results', sa.Column('website_url', sa.Text(), nullable=True))
    
    # Add website_evidences field to research_runs (nullable=False to match model)
    op.add_column('research_runs', sa.Column('website_evidences', sa.JSON(), nullable=False, server_default='[]'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_runs', 'website_evidences')
    op.drop_column('search_results', 'website_url')
    op.drop_column('search_results', 'website_domain')
    op.drop_column('search_results', 'competitor_name')
    op.drop_column('search_results', 'discovery_source')
    # ### end Alembic commands ###
