"""Add PatentDocument model

Revision ID: 2348567ad0b9
Revises: cb96565b4162
Create Date: 2026-08-06 15:25:23.371661+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic
revision: str = '2348567ad0b9'
down_revision: str | None = 'cb96565b4162'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patent_documents',
    sa.Column('patent_number', sa.String(), nullable=False),
    sa.Column('jurisdiction', sa.String(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('examples', sa.Text(), nullable=True),
    sa.Column('experimental_section', sa.Text(), nullable=True),
    sa.Column('manufacturing_section', sa.Text(), nullable=True),
    sa.Column('polymerization_section', sa.Text(), nullable=True),
    sa.Column('claims', sa.Text(), nullable=True),
    sa.Column('cpc', sa.Text(), nullable=True),
    sa.Column('ipc', sa.Text(), nullable=True),
    sa.Column('publication_date', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patent_documents_id'), 'patent_documents', ['id'], unique=False)
    op.create_index(op.f('ix_patent_documents_patent_number'), 'patent_documents', ['patent_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patent_documents_patent_number'), table_name='patent_documents')
    op.drop_index(op.f('ix_patent_documents_id'), table_name='patent_documents')
    op.drop_table('patent_documents')
    # ### end Alembic commands ###
