"""Add jurisdictions to research_runs

Revision ID: 7f5c6cf0bd4c
Revises: 2348567ad0b9
Create Date: 2026-08-07 09:14:53.393272+00:00
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '7f5c6cf0bd4c'
down_revision: str | None = '2348567ad0b9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('research_runs', sa.Column('jurisdictions', postgresql.JSON(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('research_runs', 'jurisdictions')
    # ### end Alembic commands ###
